import express from 'express'; import db from '../lib/db.js'; import {requireAuth,requireAdmin} from '../lib/auth.js';
const router=express.Router();
router.use(requireAuth, requireAdmin);
router.get('/users', (_req,res)=>res.json(db.users.list()));
router.get('/subscriptions', (_req,res)=>res.json(db.subs.list()));
router.post('/activate', (req,res)=>{const {email,plan='monthly',days=30}=req.body||{}; if(!email) return res.status(400).json({message:'email'});
  const expiresAt=new Date(Date.now()+days*86400000); return res.json(db.subs.upsert({email,plan,expiresAt,status:'active'}));});
router.post('/pause', (req,res)=>{const {email}=req.body||{}; const s=db.subs.get(email); if(!s) return res.status(404).json({message:'not found'});
  s.status='paused'; db.subs.upsert(s); res.json(s);});
router.post('/cancel', (req,res)=>{const {email}=req.body||{}; const s=db.subs.get(email); if(!s) return res.status(404).json({message:'not found'});
  s.status='cancelled'; db.subs.upsert(s); res.json(s);});
router.post('/extend', (req,res)=>{const {email,days=7}=req.body||{}; const s=db.subs.get(email); if(!s) return res.status(404).json({message:'not found'});
  const ex=new Date(s.expiresAt); ex.setDate(ex.getDate()+(+days)); s.expiresAt=ex.toISOString(); db.subs.upsert(s); res.json(s);});
router.get('/export.csv', (_req,res)=>{const arr=db.subs.list(); const csv='email,plan,expiresAt,status\n'+arr.map(x=>[x.email,x.plan,x.expiresAt,x.status].join(',')).join('\n'); res.header('Content-Type','text/csv'); res.send(csv);});
export default router;
